version: '3.8'
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: playwright
      POSTGRES_PASSWORD: playwright
      POSTGRES_DB: playwright
    restart: always
    networks:
      - playwright
networks:
  playwright:
